### ISSUE TITLE
Using Issues

### ISSUE THREAD

**Issue by victord3** [victord3/My_Project#2]
Just making sure that I am doing this right.

Also, I have fixed 1-8 and updated the edit for you to check. Let me know if it fixed it correctly and got this. 

Thanks!

**Comment by belinskyc** [comment]
Yep, got your changes and they look good.  I don't consider this a "fix" because you had it correct the first time.  I just wanted you to approach the problem from a different angle!

I will close out this Issue... 

Charlie
