### ISSUE TITLE
1-11

### ISSUE THREAD

**Issue by victord3** [victord3/My_Project#5]
1-11 Completed

**Comment by belinskyc** [comment]
Just found out that something in the Rstudio-Git-GitHub connection is broken now that I'm in Vietnam.  This will be a fun little challenge.  Luckily, I can still download your project from GitHub...

I am making edits to this lesson and going to encourage the use of single operators (&, |) over the double operators (&&, ||). The single operators are more universal in R.  They can both be used in the examples in this lesson.  When you are comparing all the values in two vector at once then you need to use single operator (creating a TRUE/FALSE vector -- something I will be adding to the lesson).  There is only a rare, and pretty advanced, situation where you need to use double.

The reason I originally went with double in the lesson is that the double operator in most programming languages is functionally like the singles in R. 

part D:
Slightly off in you logic -- guessing just a misread of the question...

**Comment by victord3** [comment]
Okay I changed the doubles to singles and I changed the logic in D (definitely misread it).

**Comment by belinskyc** [comment]
Looks good.  And the only thing to remember in the future is that single operators in R have about the same functionality as double operators in other languages.  R just wanted to be different!
